apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-unittest-app
spec:
  selector:
    matchLabels:
      run: python-unittest-app
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: python-unittest-app
    spec:
      containers:
      - name: python-unittest-app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
